import type { Metadata } from "next";
import "./globals.css";
import "./resets.css";

export const metadata: Metadata = {
  title: "Promptopia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="main">
          <div className="gradient" />
        </div>

        <div className="app">{children}</div>
      </body>
    </html>
  );
}
